version: "3"

services:
  task_canvas_web:
    build:
      context: ./frontend
    ports:
      - "${NEXT_PORT}:3000"
    depends_on:
      - task_canvas_api
    env_file:
      - .env.test
    volumes:
      - type: bind
        source: ./frontend
        target: /task-canvas/frontend
    networks:
      - task_canvas_network

  task_canvas_api:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "${GO_PORT}:8080"
    networks:
      - task_canvas_network
    env_file:
      - .env

networks:
  task_canvas_network:
    driver: bridge
