name: "CI Backend"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/ci-backend.yaml"
      - "backend/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: "read"

jobs:
  ci-backend:
    name: lint

    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: "backend/go.mod"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: ./backend

      - uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: "./backend"

      - name: Build
        run: |
          cd ./backend
          go build -v ./...

      - name: Test
        run: |
          cd ./backend
          go test ./...

